<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyTitle>limbusxbtd6</AssemblyTitle>
    <Version>1.0.0</Version>
    <Description>Limbus Company Total Conversion Mod for BTD6</Description>
    <Authors>you</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Btd6ModHelper">
      <HintPath>lib/Btd6ModHelper.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
